### PR TITLE
Add zapthreads

### PR DESCRIPTION
**Pull request by franzaps**
Added the comments component in one line, it's working!

nostr.cooking doesn't seem to support dark mode so there the colors are a bit off

Check out https://github.com/fr4nzap/zapthreads for tweaks like CSS variables and disabling features, or just let me know

### CODE REVIEW

**Comment by github-tijlxyz** [comment]
Hello, this look pretty good:)
But a few things:
 - We should or remove the zaps/likes from the comments and use the existing one or remove the existing zap system. I would suggest adding this at least `disable={'likes,zaps,replyAnonymously'}`
 - About integration: It would be amazing if the user also links to their page on nostr.cooking, like `https://nostr.cooking/user/npub1...`, I tested the urlPrefixes thing for this, but can't get it to work.
 - Can't we just pass the private key if someone is manually logged in with private key? Otherwise people logged in using nsec can't use comments.

**Comment by franzaps** [comment]
Sure! Can you pass me the URL prefixes you want? For `naddr`, `npub`, `nprofile`, `nevent`, `note`, `tag`.

Regarding logging in with nsec I would need to support that in a future release. I'll try to have a look at that this week

**Comment by github-tijlxyz** [comment]
We basically only have `https://nostr.cooking/recipe/[naddr or event hex]` and `https://nostr.cooking/user/[npub or hex public key]` at the moment. Others can just be disabled or link to another client.

Thank you again for the contributions, would love to see login with private key.

**Comment by franzaps** [comment]
Cool. Just curious, where would you like tags (for example) to link to? At the moment they go to Habla but trying to figure out what sensible defaults should be

**Comment by github-tijlxyz** [comment]
For defaults; you could use a more general web client like Coracle or Snort. There are also these hub sites, where you can copy it or click on a client to open. But maybe even better, let the browser/device choose themselves. You can just like a `nostr:...`, and on **most** devices/browsers it **should** open a client selected (following [NIP21](https://github.com/nostr-protocol/nips/blob/master/21.md)). Only problem is that some operating systems or browsers don't have good support for this.

**Comment by franzaps** [comment]
@github-tijlxyz Ready. On `0.3.2` (just released) the `npub` attribute supports both npub & nsec . I'll leave you to pass the right data

Good to merge you think?

**Review by github-tijlxyz — APPROVED** [review]

**Comment by github-tijlxyz** [comment]
Thanks for your help, I added the nsec support to this PR

**Pull request merged**
